name: 'Test Caching'

on: [ push, pull_request ]

jobs:
    CacheWriteRestore:
        name: 'Cache something'
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Cache Test
                uses: actions/cache@v2
                with:
                    path: '/foo/bar'
                    key: ${{ runner.os }}-test-${{ hashFiles('./cache.sh') }}
                    restore-keys: |
                        ${{ runner.os }}-test-

            -   name: Write something
                run: |
                    ./cache.sh
