name: 'Test Caching'

on: [ push, pull_request ]

jobs:
    CacheWriteRestore:
        name: 'Cache something'
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                one: [ 'one' ]
                two: [ 'two', 'three' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Current dir
                id: current
                run: |
                    echo "::set-output name=dir::$(pwd)"
                    echo "::set-output name=timestamp::$(date +"%s")"

            -   name: Cache Test
                uses: actions/cache@v2
                with:
                    path: ${{ steps.current.outputs.dir }}/foo/bar
                    key: ${{ runner.os }}-test2-${{ steps.current.outputs.timestamp }}
                    restore-keys: |
                        ${{ runner.os }}-test2-

            -   name: Write something
                run: |
                    echo ${{ steps.current.outputs.timestamp }} ${{ matrix.one }} ${{ matrix.two }}
                    ./cache.sh ${{ steps.current.outputs.dir }} ${{ steps.current.outputs.timestamp }}
